### ISSUE TITLE
Error Wifi AP! M117 192.168.0.1

### ISSUE THREAD

**Issue by c128** [luc-github/ESP8266#29] opened 2015-08-03 05:45 UTC
compiled without change anything in source give error
after try with change ip, name etc nothing to do and print "Error Wifi AP! M117 192.168.0.1" 

i think not initialize esp to ap mode
my version of esp8266 is 01
http://www.esp8266.com/wiki/doku.php?id=esp8266-module-family#esp-01
arduino version 1.6.5

esp compiled with other source working 
for example this is ok and esp go to ap mode
https://github.com/esp8266/Arduino/blob/ea302aab05480ad36c076b618abb642b1eb1893b/hardware/esp8266com/esp8266/libraries/DNSServer/examples/CaptivePortal/CaptivePortal.ino

**Comment by luc-github** [comment] 2015-08-03 05:53
do you use latest staging module ?
I usually use station mode after AP mode
I try try to reproduce issue

**Comment by c128** [comment] 2015-08-03 06:14
arduino ide is reinstalled with latest staging module: http://arduino.esp8266.com/package_esp8266com_index.json
http://arduino.esp8266.com/staging/package_esp8266com_index.json

no errors after compiling

**Comment by luc-github** [comment] 2015-08-03 09:07
can you also share what settings you are using?
it may help to reproduce issue because AP mode is working reading default configuration

**Comment by c128** [comment] 2015-08-03 14:03
try with ubuntu and arduino ide same config 
when compiling there is only problem to find lib (i think problem only for linux):

in webinterface.cpp

#include <PgmSpace.h>
replace with
#include <pgmspace.h>

but esp not start with AP 

i make video with my procedure

**Comment by luc-github** [comment] 2015-08-03 14:13
yes my bad I did not compiled on mac/linux - thanks for pointing this
fixed with https://github.com/luc-github/ESP8266/commit/8dd8ec207d602a81f378cc9272083ad0861f68e4

still checking the AP error your get as cannot reproduce

**Comment by luc-github** [comment] 2015-08-03 15:20
one additional information - you need to reset EEPROM as when flashing it does not erase EEPROM area - so if the EEPROM is corrupted in some way - AP won't start
you must plug module then connect GPIO2 to GND 2s after plug and before 10s - this will recreate a clean EEPROM

**Comment by luc-github** [comment] 2015-08-04 01:43
can you share what settings were used on ESP to settup AP ? as I am not able to reproduce issue
I changed IP, Channel, etc and no issue

**Comment by c128** [comment] 2015-08-04 08:48
nothing to do!
same photo:
![100_1834](https://cloud.githubusercontent.com/assets/6648072/9056869/25c6c0b2-3ac0-11e5-84b4-c68f0dc156af.JPG)
![100_1839](https://cloud.githubusercontent.com/assets/6648072/9056870/25cb6a86-3ac0-11e5-899d-dc0674903e95.JPG)

**Comment by c128** [comment] 2015-08-04 08:51
i can program this without problem
http://ez-gui.com/manual/multiwii-clearflight-wifi-to-ezi-gui-how-to/
or this
http://www.arduinesp.com/wifiwebserver

**Comment by luc-github** [comment] 2015-08-04 08:51
this is flash settings -  I am talking about AP settings did you used to reproduce the issue as SID ESP8266 and default settings are working as you mentionned you were able to change them

**Comment by luc-github** [comment] 2015-08-04 08:53
from this page <img SRC="https://raw.githubusercontent.com/luc-github/ESP8266/master/Page3.png">

**Comment by luc-github** [comment] 2015-08-06 04:21
any update ? I still cannot reproduce issue

**Comment by c128** [comment] 2015-08-06 04:36
i think power problem with my USB
wait for testing with other pc

**Comment by luc-github** [comment] 2015-08-06 04:38
Ok

**Comment by c128** [comment] 2015-08-12 15:50
problem is impedance  of push button switch for program and reset 
you need good electronics for program this device

i make shield for esp8266 pin compatible with bluetooth hc-05 and optical isolated
for now prototype is working very well 
![foto2](https://cloud.githubusercontent.com/assets/6648072/9228840/7bf143c4-4144-11e5-81d9-b036e673937f.png)

**Comment by luc-github** [comment] 2015-08-12 15:54
ok great,so issue can be closed ?

**Comment by c128** [comment] 2015-08-12 15:54
yes is ok
now testing 3d printer

**Closed** 2015-08-12 16:10 UTC
Labels: Waiting for details
