### ISSUE TITLE
[BUG]ESP3D can't control ender3 but usb can

### ISSUE THREAD

**Issue by a491113058** [luc-github/ESP8266#517] opened 2020-10-21 09:11 UTC
**Describe the bug**
I use the ESPA motherboard. Now I can open a web page or upload files to an SD card, but I can't control the printer.
The printer can be linked and controlled through serial port.
So what's wrong with the hardware? I don't know what went wrong

**Screenshots**
![asd](https://user-images.githubusercontent.com/49088398/96699014-5bd0ef00-13c0-11eb-9023-709f6c200a42.jpg)

**ESP3D Firmware:**
[ESP420]plain
Chip ID: 57576
CPU Frequency: 240Mhz
CPU Temperature: 76.7C
Free memory: 161.14 KB
SDK: v3.2.3-14-gd3e562907
Flash Size: 4.00 MB
Available Size for update: 1.25 MB
Available Size for SPIFFS: 1.31 MB
Baud rate: 115200
Sleep mode: None
Web port: 80
Hostname: marlinesp
Active Mode: STA (AC:67:B2:D9:E8:E0)
Connected to: PDCN
Signal: 100%
Phy Mode: 11n
Channel: 1
IP Mode: DHCP
IP: 192.168.99.22
Gateway: 192.168.99.1
Mask: 255.255.255.0
DNS: 192.168.99.1
Disabled Mode: AP (AC:67:B2:D9:E8:E1)
FW version: Marlin 2.0.7 (ESP3D:1.0.8)

**Target Firmware:**
FIRMWARE_NAME :  Marlin 2.0.7
 
 tip: to get firmware info type `M115` in console    

**Board used (please complete the following information):**
 - MCU: ESP32
 - Name:ESPA V1.2

**Additional context**
Wiring, decoded stack, etc...

**Comment by luc-github** [comment] 2020-10-21 10:07
I am guessing it is Marlin configuration problem - they changed settings recently
https://github.com/MarlinFirmware/Marlin/pull/19812#issuecomment-713080930

enable https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/Configuration.h#L112 
and it should communicate

**Comment by exilaus** [comment] 2020-10-21 12:15
![image](https://user-images.githubusercontent.com/2852823/96718003-a85c0080-13a7-11eb-8cb1-fe09ad866ded.png)
just for explain clean configure serial port as in picture and websoket be initialized.

**Comment by a491113058** [comment] 2020-10-21 12:51
This is indeed the reason, and it can work. Thank you very much!
But I encountered a new problem, the limit switch of the X axis is closed, which will cause the network service to restart.

**Comment by luc-github** [comment] 2020-10-21 12:52
what do you mean ?

**Comment by a491113058** [comment] 2020-10-21 12:56
X limit switch is triggered == will cause the network service to restart.

Please see the picture:
![333](https://user-images.githubusercontent.com/49088398/96722373-e117cc00-13df-11eb-8e7b-6c4091b23b0e.jpg)

**Comment by luc-github** [comment] 2020-10-21 12:59
you have ESPA so did you applied the patch I suggested to vivian-ng ? 
https://github.com/MarlinFirmware/Marlin/pull/19812#issuecomment-713204065

The issue is not in EP3DLib - the board is reset due to above issue

**Comment by luc-github** [comment] 2020-10-21 14:28
here the path of the change need to be done https://github.com/MarlinFirmware/Marlin/blob/2.0.x/Marlin/src/HAL/ESP32/HAL.cpp#L89
you can just delete `i2s_init();` in your case - it is more easy than type ;)

**Comment by exilaus** [comment] 2020-10-21 15:10
Luc placing in pull this fix too for esp32.  today at office little difficut to manage that but surely in future bugfix can remove that issue for no i2s steppers board

**Comment by luc-github** [comment] 2020-10-21 15:28
@exilaus yes thank you

**Comment by luc-github** [comment] 2020-10-24 08:22
@a491113058 fix has been merged in bug-fix already - does it fix your issue ?

**Comment by luc-github** [comment] 2020-10-30 15:49
I guess no more issue

**Closed as completed by luc-github** 2020-10-30 15:49 UTC
Labels: bug, Cannot Duplicate, ESP3D 2.X, outdated
