### ISSUE TITLE
Internet access error

### ISSUE THREAD

**Issue by Stephano2000** [luc-github/ESP8266#853] opened 2023-01-30 00:25 UTC
Hi,
In order to provide remote internet access to the ESP3D UI, i forwarded ports 80 and 81 to a public server server:10554 and server:10555 respectively. However the UI keeps disconnecting with a websocket error after 1  or 2 seconds. Accessing ESP3D locally works fine.
I am not sure whether this is a bug or i am just not doing the correct port forwarding, noting that ports 80 and 81 are not available on the public server.
- ESP3D v3
- ESP32-CAM

**Comment by luc-github** [comment] 2023-01-30 01:41
yes this is due to a workaround for apple captive portal, it use local ip for websocket instead of `document.location.host` provided in address bar
It is an issue I forget to handle  orz... I need to think about it

**Comment by luc-github** [comment] 2023-01-30 01:49
well actually I use `ws://${document.location.hostname}:${connectionSettings.current.WebSocketPort}${path}` so my assumption is wrong it was already fixed

can you check the dev tool of your browser to see what url is used and what is the error ?
it could be due to antivirus / antispam software as you are no more on local area

**Comment by Stephano2000** [comment] 2023-01-30 09:54
It seems it's still after port 81:
"Firefox can’t establish a connection to the server at ws://45.33.36.41:81/."
Where can i modify the 81 in source code to test? I could make it 10555 to just check if the bug shows up or not.

**Comment by luc-github** [comment] 2023-01-30 09:56
ok so check what could block on your computer, disable antivirus , firewall to check which is the blocking point

**Comment by Stephano2000** [comment] 2023-01-30 09:58
Antivirus and firewall are not in the picture.
Why would the web browser try to open the websocket at port 81 while the base port is 10554?

**Comment by luc-github** [comment] 2023-01-30 09:59
webui websocket use 81, it use webserver port +1
defaut webserver port is 80, so webui websocket use  80+1

**Comment by luc-github** [comment] 2023-01-30 10:03
I did not handled you change websocket port, for nat
so issue is there

**Comment by luc-github** [comment] 2023-01-30 10:14
I will push a solution later tonight, I am out now

**Comment by Stephano2000** [comment] 2023-01-30 11:42
I changed the HTTP protocol port to 10554 in the UI, forwarded ports 10554 and 10554 to 10554 and 10555 respectively, and there are no disconnections anymore.
So the browser itself should set the websocket port to the HTTP host port + 1 so that the websocket connection is successful.

**Comment by luc-github** [comment] 2023-01-30 11:49
yes because you use same as used by FW
you can have a look by just typing [ESP800] in web ui terminal, it will show the webui websocket port

**Comment by Stephano2000** [comment] 2023-01-30 12:14
Maybe I didn't explain myself clearly, or misunderstood your statement.
What I meant was that the Web UI javascript/code should be modified so that it attempts to open (HTTP request port)+1 instead of relying on the port number communicated by ESP3D.

I have gone through the ESP3D code which led me to check out both [ESP400] and [ESP800]

**Comment by luc-github** [comment] 2023-01-30 13:14
yes as I wrote I did not handled the case user change the port by nat - it currently use the port provided by [ESP800] - I will fix it in web UI by collecting current http port and add +1 to it to make the webui websocket port

**Comment by luc-github** [comment] 2023-01-30 13:56
can you test this one and feedback ?
[index.html.gz](https://github.com/luc-github/ESP3D/files/10536342/index.html.gz)

**Comment by Stephano2000** [comment] 2023-01-30 14:17
It bricked the UI. The UI flashed "connecting" for a fraction of a second then shows a continuously spinning arc.
What was the force upload url (in the hope that it works to avoid a reflash)?

**Comment by luc-github** [comment] 2023-01-30 14:29
arg you tested in local with port 80 not remote, I missed this case orz 
I fixed in this one 
[index.html.gz](https://github.com/luc-github/ESP3D/files/10536653/index.html.gz)
Sorry ...

**Comment by luc-github** [comment] 2023-01-30 14:30
use `http://your ip?forcefallback=yes` to update because ui is broken

**Comment by Stephano2000** [comment] 2023-01-30 14:39
> arg you tested in local with port 80 not remote, I missed this case orz I fixed in this one [index.html.gz](https://github.com/luc-github/ESP3D/files/10536653/index.html.gz) Sorry ...

I can confirm that this one doesn't disconnect both locally, and remotely with forwarded ports.
Thanks

**Comment by luc-github** [comment] 2023-01-30 14:44
Cool, thank you for the feedback - I need to update the test server and do a rebuild for all target and update some docs
It will be done tomorrow -  here it is almost 23h and doing now is recipe to trouble / mistake, I did enough for tonight ;)

**Comment by liqijian101** [comment] 2023-01-31 11:48
Can HTTPS be supported

**Comment by luc-github** [comment] 2023-01-31 11:51
current esp32 arduino webserver does not have this feature, it is planned as far I know

**Comment by liqijian101** [comment] 2023-01-31 14:24
The webpage displays "Webdevsocket connection error"
- [x] Enable websocket
- [ ] Port 8282

**Comment by luc-github** [comment] 2023-01-31 23:59
@liqijian101 as issue here is confirmed resolved  by OP- your issue is different - so please open new issue for your problem with full reproduction steps

**Comment by luc-github** [comment] 2023-02-01 00:14
@Stephano2000  fixed in latest webui (a29), thank you for raising it

**Closed as completed by luc-github** 2023-02-01 00:14 UTC
Labels: bug, Work in progress, ESP3D 3.X, outdated
